### ISSUE TITLE
Test setup error: test tree is empty

### ISSUE THREAD

**Issue by tmczhangtielin** [sferes2/sferes2#18]
hi,  jbmouret:
   I follow the https://github.com/jbmouret/sferes2/wiki/Compilation to build the sferes2, all the versions of the libraries are the same as the link, include the boost and opencv. 
  It seems that the ./waf configure and build is right. However, when I do the ./waf check. It shows that:
*** No errors detected
Test setup error: test tree is empty
default/tests/tests_modif_diversity ............OK 
……
default/modules/map_elite/test_map_elite ...FAILED 
……
debug/modules/nn2/test_hyper_nn ............FAILED 
……
debug/modules/map_elite/test_map_elite .....FAILED 

  The ……means that items are check okay, I omit them. 
May you give me some suggestion? 
Great thanks.

**Comment by jbmouret** [comment]
Thank you for your feedback.

The failed tests are because they are not up-to-date (and in optional modules). 

For the tree test, I don't see the error on my computer. Did you compile on Linux or OSX? Which Linux?

regards,
-- JBM

**Comment by tmczhangtielin** [comment]
On Ubuntu 14.04 LTS.  My compile method is like this:
Install Sferes2
1) Update Opencv2.4.10
 after installed use pkg-config --modversion opencv to ensure version.

2)install boost1.52
sudo tar -zxvf boost_1_52_0.tar.gz
cd  boost_1_52_0
./bootstrap.sh
./b2 install
 use locate boost to ensure version.

3)Compile Sferes2
sudo apt-get install libtbb-dev libeigen2-dev python-simplejson libgoogle-perftools-dev
sudo apt-get install libgoogle-glog-dev 
libgflags-dev liblmdb-dev
go to sfere2 page
./waf configure (OK)
./waf build (OK maybe)
./waf check . Test tree is empty error occur. 

Here the end of compile result may give some help:
……
phi_ij:0.81 1
0 0.136798
1 0.510003
2 0.566504
3 0.271217
4 -0.192494
Test case nn_osc did not check any assertions
Leaving test case "nn_osc"; testing time: 60185mks
Leaving test suite "nn_osc"
*** No errors detected
Running 1 test case...
Entering test suite "dnn"
Entering test case "gen_cppn"
Leaving test case "gen_cppn"; testing time: 66101mks
Leaving test suite "dnn"
test tree is empty error occured. (my annotation)
--Thomas in BJ

**Comment by silgon** [comment]
I'm having the same error (using also **Ubuntu 14.04 LTS**). I add the important part of  `./waf configure`.
```
boost headers                            : Version 1_54 (/usr/include) 
library boost_serialization              : not found 
library boost_filesystem                 : not found 
library boost_system                     : not found 
library boost_unit_test_framework        : not found 
library boost_program_options            : not found 
library boost_graph                      : not found 
library boost_mpi                        : not found 
library boost_python                     : not found 
library boost_thread                     : not found 

```

Even though it detect the boost headers, the libraries are not found. Then I'm not able to compile because of this. Maybe there's something missing?

@tmczhangtielin did you compile boost from source and did it work? because the only difference I see it's that the version you installed was 1.52 and the version of the *ubuntu 14.04 binaries* is 1.54.

**Comment by jbmouret** [comment]
Hi

This is a known problem on the last version of Ubuntu (they moved the boost libraries to a /usr/lib64 or something like this instead of the classic unix paths like /usr/lib or /usr/local/lib). The easiest short-term fix is to add a symbolic link to the boost libraries in a standard path (like /urs/lib). 

I will try to update the scripts soon but this is not as simple as it seems.

Best regards,
� Jean-Baptiste mMouret

On 29 May 2015, at 16:38, silgon <notifications@github.com> wrote:

> I'm having the same error (using also Ubuntu 14.04 LTS). I add the important part of ./waf configure.
> 
> boost headers                            : Version 1_54 (/usr/include) 
> library boost_serialization              : not found 
> library boost_filesystem                 : not found 
> library boost_system                     : not found 
> library boost_unit_test_framework        : not found 
> library boost_program_options            : not found 
> library boost_graph                      : not found 
> library boost_mpi                        : not found 
> library boost_python                     : not found 
> library boost_thread                     : not found 
> 
> 
> Even though it detect the boost headers, the libraries are not found. Then I'm not able to compile because of this. Maybe there's something missing?
> 
> @tmczhangtielin did you compile boost from source and did it work? because the only difference I see it's that the version you installed was 1.52 and the version of the ubuntu 14.04 binaries is 1.54.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by silgon** [comment]
Yeah, just checked, it's in `/usr/lib/x86_64-linux-gnu`, apparently they did it to have support multiarch as explained [here](http://askubuntu.com/a/449351/269279). As for the symbolic links, right now I hesitate since `# ls /usr/lib/x86_64-linux-gnu/ | grep boost` throws me 109 results for which I'll have to do a symbolic link in `/usr/lib`. I'll check it out later though. Thanks =)

**Comment by jbmouret** [comment]
Yes, you can easily do it:
ln -s  /usr/lib/x86_64-linux-gnu/libboost* .

I will try to work on a patch soon.

On 29 May 2015, at 17:12, silgon <notifications@github.com> wrote:

> Yeah, just checked, it's in /usr/lib/x86_64-linux-gnu, apparently they did it to have support multiarch as explained here. As for the symbolic links, right now I hesitate since # ls /usr/lib/x86_64-linux-gnu/ | grep boost throws me 109 results for which I'll have to do a symbolic link in /usr/lib. I'll check it out later though. Thanks =)
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by silgon** [comment]
I was avoiding to add more things in my `/usr/lib/` folder, but yeah, it builds and apparently it works fine adding those symbolic links. I'll be testing it later, thanks ;).
